# Application
spring.application.name=DRIVER-CLIENT-SERVICE
server.port=8082


# Config Server (désactivé temporairement)
spring.config.import=optional:configserver:


# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/driver_client_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=driver_client_user
spring.datasource.password=driver_client_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud


# OAuth2 Resource Server (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/deliverx
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/deliverx/protocol/openid-connect/certs


welcome.message=Welcome to Driver & Client MS


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Actuator
management.endpoints.web.exposure.include=health,info