# Application
spring.application.name=DRIVER-CLIENT-SERVICE
server.port=8082


# Config Server (désactivé temporairement)
spring.config.import=optional:configserver:


# H2 Database
spring.datasource.url=jdbc:h2:file:./data/driverclientdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_aud


# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# OAuth2 Resource Server (Keycloak)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/deliverx
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/deliverx/protocol/openid-connect/certs


welcome.message=Welcome to Driver & Client MS


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# Actuator
management.endpoints.web.exposure.include=health,info